---
title: "Untitled"
author: "Alex Long"
date: "November 20, 2019"
output:
  html_document: default
  pdf_document: default
---

```{r}


A = c(0,	1,	0,	1,	0,	0,	0,	0,	0)
B = c(1,	0,	1,	0,	1,	0,	0,	0,	0)
C = c(0,	1,	0,	0,  0,  1,  0,	0,	0)
E = c(1,	0,	0,	0,	1,	0,	1,	0,	0)
F = c(0,	1,	0,	1,	0,	1,	0,	1,	0)
G = c(0,	0,	1,	0,	1,	0,	0,	0,	1)
I = c(0,	0,	0,	1,	0,	0,	0,	1,	0)
J = c(0,	0,	0,	0,	1,	0,	1,	0,	1)
K = c(0,	0,	0,	0,	0,	1,	0,	1,	0)

Anorm = c(0,	.5,	0,	.5,	0,	0,	0,	0,	0)
Bnorm = c(.33,	0,	.33,	0,	.33,	0,	0,	0,	0)
Cnorm = c(0,	.5,	0,	0,	0,	.5,	0,	0,	0)
Enorm = c(.33,	0,	0,	0,	.33,	0,	.33,	0,	0)
Fnorm = c(0,	.25,	0,	.25,	0,	.25,	0,	.25,	0)
Gnorm = c(0,	0,	.33,	0,	.33,	0,	0,	0,	.33)
Inorm = c(0,	0,	0,	.5,	0,	0,	0,	.5,	0)
Jnorm = c(0,	0,	0,	0,	.33,	0,	.33,	0,	.33)
Knorm = c(0,	0,	0,	0,	0,	.5,	0,	.5,	0)

W <- cbind(A,B,C,E,F,G,I,J,K)
Wnorm <- cbind(Anorm,Bnorm,Cnorm,Enorm,Fnorm,Gnorm,Inorm,Jnorm,Knorm)

W <- Wnorm
za = c(0.5,	-0.5,	0.5,	-0.5,	0.5,	-0.5,	0.5,	-0.5,	0.5)
zb = c(0.5625,	0.5625,	0.5625,	0.5625,	-0.4375,	-0.4375,	0.5625,	-0.4375,	-0.4375)
zc = c(0.375,	0.375,	0.375,	0.375,	-0.625,	-0.625,	0.375,	-0.625,	-0.625)

# za = c(0.4444,	-0.5556,	0.4444,	-0.5556,	0.4444,	-0.5556,	0.4444,	-0.5556,	0.4444)
# zb = c(0.4444,	0.4444,	0.4444,	0.4444,	-0.5556,	-0.5556,	0.4444,	-0.5556,	-0.5556)
# zc = c(0.4444,	0.4444,	0.4444,	0.4444,	-0.5556,	-0.5556,	0.4444,	-0.5556,	-0.5556)

print(W)
print(za)

```

```{r}

Ia1 <- t(za) %*% W %*% za
Ia2 <- t(za) %*% za
Ia <- Ia1 / Ia2

Ib1 <- t(zb) %*% W %*% zb
Ib2 <- t(zb) %*% zb
Ib <- Ib1 / Ib2

Ic1 <- t(zc) %*% W %*% zc
Ic2 <- t(zc) %*% zc
Ic <- Ic1 / Ic2

print(Ia)
print(Ib)
print(Ic)

```

